### PR TITLE
Meson

### PR DESCRIPTION
**Pull request by keszybz**
This does not include test-script.sh generation or running in the test suite. It depends how the transition would look. My inclination would be to drop autoools support and then rename test-script.sh.in to test-script.sh, and push the builddir and other dirs as variables into the script. Under meson this is easier then processing the .in file, and the script would be more readable I think. Alternatively, if support for autotools is to be maintained, support can be added without doing the rename, but it'd be more involved.

I didn't test this apart from running the tests and installing into $DESTDIR. Caveat emptor.

### CODE REVIEW

**Comment by poettering** [comment]
looks good to me, except for the test thing. I am all for simply dropping autotools support entirely, right now, and go meson all the way. Maintaining both in parallel sounds like something we should avoid if we can.

(That said @zonque is using this stuff, and he might not be as meson happy as me? @zonque say something)

Also, the liblzma dep in the meson script should be updated to 5.1.0, following 02d6072dfb775f84e58aca210e59bba654932e14 which I merged today.

Thanks for working on this, much appreciated!

**Comment by zonque** [comment]
Okay, I tried this now and it worked with one minor change - the latest version of meson currentöy available on OpenEmbedded is `0.37.1`. I downgraded the requirement in `meson.build` and everything worked fine. Unless there is a strong reason not to do it, let's not require something that causes major pain downstream :)

Thanks!

**Comment by keszybz** [comment]
I added the generation of test-script.sh and test-nbd.sh. (I didn't really understand why they were done this way, but now I see that this allow them to be run from the command line easily). test-nbd.sh passes, but test-script.sh fails with some error message, which I don't know how to debug (see last commit). But maybe it's not meson-related, since autotools build fails too.

I lowered the meson version to 0.37.1. I'm not specifically using anything too recent, but I didn't test it with older versions either. I'm relying on @zonque's testing here.

**Comment by poettering** [comment]
hmm, the test-script.sh test ultimately starts a tiny http server using python's http support and then tries to retrieve data from it. it's a bit crude right now, as we simply wait for 3s before assuming the server is up...

Does test/http-server.py work for you if you call it on the command line? It expects a directory to serve as parameter.

**Comment by zonque** [comment]
Hmm, that's odd. Current master (after the merge) fails like this:

```
[13:30:14][Step 3/4] | Meson encountered an error in file meson.build, line 162, column 0:
[13:30:14][Step 3/4] | Arguments must be strings.
[13:30:14][Step 3/4] | ERROR: meson failed
```

**Comment by zonque** [comment]
And before that, it says

```
[13:30:14][Step 3/4] | Program test-files/test-files.sh found: YES (/home/teamcity/worker/poky/build/tmp-glibc/work/aarch64-linux/casync/master+git-AUTOINC+91eff6f8c4-r0/git/test-files/test-files.sh)
[13:30:14][Step 3/4] | Element not a string: [<File: test-script.sh>]
```

**Comment by zonque** [comment]
This seems to be an issue that is resolved with meson 0.40. I've sent out a patch to update it in OpenEmbedded. You might want to raise the dependency again.

**Comment by keszybz** [comment]
> Does test/http-server.py work for you if you call it on the command line?

Yikes,  `localhost` wasn't resolvable ;) `/etc/nsswitch.conf` was mangled, not sure if this was my fault or some rpm scriptlet which got confused by unusual `hosts:` line. We really need to get rid of those sed scripts and make /etc/nsswitch.conf have our modules by default. Too late for F26 with that, but I'll try to get it done for F27.

Now it passes.

I wonder if it would be possible to split test-script.sh into a few smaller pieces. meson will run tests in parallel if it can.

**Pull request merged**
