### PR TITLE
casync gc

### PR DESCRIPTION
**Pull request by keszybz**
Further work is probably needed. I'm putting this out here to receive comments on the general direction.
I made a ~3GB .castr here, and `gc` runs quickly enough so that I don't think that any performance work is needed.

I'm aware of at least one RFE: if both compressed and uncompressed chunks (for the same chunk id) are present, they will not be de-duplicated. We should probably trim all but the smallest chunk with the same id.

### CODE REVIEW

**Comment by keszybz** [comment]
Pfff, this was mind-numbingly boring. I fixed a buglet in the gc reporting path, and replaced fprintf's with log_error and log_info.

**Comment by keszybz** [comment]
@poettering any chance you could review this?

**Comment by poettering** [comment]
sorry, for not reviewing this so far. It's the next item on my todo list

(note that the PR is currently unmergable though, needs a rebase)

**Comment by poettering** [comment]
So, code looks very good. Two points:

1. the one reason I didn't implement this so far was that eventually I figure we need some kind of remoting concept for this, i.e. a client should be able to GC stored on some remote store. And this means CaRemote needs to learn about this in some way. The client side would have to compile the list of chunk ids to keep and then push that to the other side, which removes everything not listed. But i figure we can add this later. Your code is nicely composable enough to make alter it like that later on.

2. So far I avoided to keep large hash tables of chunk IDs in memory, and always (mis-)used temporary dirs with symlinks in /var/tmp instead as hashtables, because I wanted to make it possible to grow this without bounds. That's btw, why there currently is not hash table in use in casync: it's all stored in the fs, the fs implementation is my hash table (albeit a slow one). I think we need to fix this eventually, but I figure for now this is good enough, in particular as it's going to be much faster than my "on-disk-hashtables"... An ideal algorithm would probably be to start with in-memory hash tables, before dumping things to /var/tmp. For now we should probably enforce some size limit on the hash table though I guess?

The code looks great otherwise. If you press me hard to find something to nitpick about then it'd be "while(true)" → "for (;;)"… ;-)

**Comment by poettering** [comment]
(and sorry for being slow with reviewing this)

**Comment by poettering** [comment]
(and as mentioned, needs a rebase to be mergable)

**Comment by keszybz** [comment]
Updated.

**Comment by keszybz** [comment]
Rebased again.

**Comment by poettering** [comment]
lgtm

**Pull request merged**
