### PR TITLE
Endianness and int size fixes

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
The last commit makes tests pass (as non-root) on all koji architectures (amd64, i386, ppc64be, ppc64le, s390x, arm, arm64).

**Comment by poettering** [comment]
patches look excellent, except for the size_t one... So far I tried to make sure that buffers in memory are always passed with a matching size as size_t, while sizes of stuff on disk as uint64_t. And I'd claim that is good that way, as it always should remind us when dealing with buffers if what we process is small enough for memory or can only be stored on disk. Now, I am sure there are some mistakes in the code regarding conversions between that, but I do think we should continue to do this differentiation, and convert only where necessary, and then explicitly do the conversion, best with an overflow check of some form.

Or in other words: if some function gets a pair of void pointer + size parameters to describe some buffer in memory then the size parameter really should be size_t...

Does that make sense?

**Comment by poettering** [comment]
I cherry picked all but the size_t patches for, I think that one needs more discussion!

**Comment by keszybz** [comment]
Hm, that's not so obvious how to do it. The offsets in the data are inherently in 64 bits, and it'd be awkward to *immediately* convert them to 32 bit. For example, UINT64_MAX is used as a marker value, and with 32 bit variable you'd need a second special value, and then remember to special case then when casting to a wider variable, etc. Instead, I think most offsets should be 64 bit, and should be cast to 32 bit at the latest possible point: before allocation or before syscalls that take a 32bit parameter. After all, `off_t` is 64 bits, so we might be able to go a long way with 32bit address space.

**Pull request merged**
